services:
  postgres:
    image: postgres:16
    container_name: blockchain_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tron1_benedikt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tron1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: