#!/usr/bin/env python3
"""
Stablecoin Visualization Script

This script reads the CSV files generated by stats.py and creates five plots:
1. Daily transacted volume for all stablecoins
2. Daily transaction count for all stablecoins
3. Daily different addresses involved in stablecoin transactions
4. Daily DeFi protocol transactions for all stablecoins
5. Daily Rollup protocol transactions for all stablecoins

All plots show days on the x-axis with different colors for each stablecoin
and include legends.
"""

import glob

import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.use('Agg')  # Use non-interactive backend


def load_stablecoin_data():
    """Load all available stablecoin daily stats CSV files"""
    stablecoin_data = {}

    # Find all daily stats CSV files
    csv_files = glob.glob("*_daily_stats.csv")

    print("Found {} stablecoin data files:".format(
        len(csv_files)))

    for csv_file in csv_files:
        # Extract stablecoin name from filename
        stablecoin_name = csv_file.replace("_daily_stats.csv", "")

        try:
            # Read the CSV file
            df = pd.read_csv(csv_file)

            # Convert date column to datetime
            df['date'] = pd.to_datetime(df['date'])

            # Extract volume and transaction count columns
            volume_col = "total_volume_{}".format(stablecoin_name)
            tx_count_col = "transaction_count"

            if volume_col in df.columns and tx_count_col in df.columns:
                # Store the data
                # Check if different_addresses and defi columns exist
                different_addr = None
                if 'different_addresses' in df.columns:
                    different_addr = df['different_addresses']

                defi_txs = None
                rollup_txs = None
                if 'defi_transaction_count' in df.columns:
                    defi_txs = df['defi_transaction_count']
                if 'rollup_transaction_count' in df.columns:
                    rollup_txs = df['rollup_transaction_count']

                stablecoin_data[stablecoin_name] = {
                    'dates': df['date'],
                    'volume': df[volume_col],
                    'transaction_count': df[tx_count_col],
                    'different_addresses': different_addr,
                    'defi_transaction_count': defi_txs,
                    'rollup_transaction_count': rollup_txs
                }
                print("  ✓ {}: {} days of data".format(
                    stablecoin_name.upper(), len(df)))
            else:
                print("  ✗ {}: Missing required columns".format(
                    stablecoin_name.upper()))

        except Exception as e:
            print("  ✗ {}: Error reading file - {}".format(
                stablecoin_name.upper(), e))

    return stablecoin_data


def create_volume_plot(stablecoin_data):
    """Create a plot showing daily transacted volume for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['volume'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='o',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Volume',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Volume (Tokens)', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_volume_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Volume plot saved as 'stablecoin_volume_plot.png'")

    return plt


def create_transaction_count_plot(stablecoin_data):
    """Create a plot showing daily transaction count for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as volume plot)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['transaction_count'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='s',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Count',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_transaction_count_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Transaction count plot saved as "
          "'stablecoin_transaction_count_plot.png'")

    return plt


def create_different_addresses_plot(stablecoin_data):
    """Create a plot showing daily different addresses for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as other plots)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        if data['different_addresses'] is not None:
            color = colors[i % len(colors)]
            plt.plot(data['dates'], data['different_addresses'],
                     label=stablecoin_name.upper(),
                     color=color,
                     linewidth=2,
                     marker='^',
                     markersize=4)

    plt.title('Daily Different Addresses in Stablecoin Transactions',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Different Addresses', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_different_addresses_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Different addresses plot saved as "
          "'stablecoin_different_addresses_plot.png'")

    return plt


def create_defi_transactions_plot(stablecoin_data):
    """Create a plot showing daily DeFi protocol transactions
    for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as other plots)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        if data['defi_transaction_count'] is not None:
            color = colors[i % len(colors)]
            plt.plot(data['dates'], data['defi_transaction_count'],
                     label=stablecoin_name.upper(),
                     color=color,
                     linewidth=2,
                     marker='D',
                     markersize=4)

    plt.title('DeFi Protocol Transactions for Stablecoins',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of DeFi Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_defi_transactions_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ DeFi transactions plot saved as "
          "'stablecoin_defi_transactions_plot.png'")

    return plt


def create_rollup_transactions_plot(stablecoin_data):
    """Create a plot showing daily Rollup protocol transactions
    for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as other plots)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        if data['rollup_transaction_count'] is not None:
            color = colors[i % len(colors)]
            plt.plot(data['dates'], data['rollup_transaction_count'],
                     label=stablecoin_name.upper(),
                     color=color,
                     linewidth=2,
                     marker='s',
                     markersize=4)

    plt.title('Rollup Protocol Transactions for Stablecoins',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Rollup Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_rollup_transactions_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Rollup transactions plot saved as "
          "'stablecoin_rollup_transactions_plot.png'")

    return plt


def print_summary_stats(stablecoin_data):
    """Print summary statistics for all stablecoins"""
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    for stablecoin_name, data in stablecoin_data.items():
        total_volume = data['volume'].sum()
        total_transactions = data['transaction_count'].sum()
        avg_daily_volume = data['volume'].mean()
        avg_daily_transactions = data['transaction_count'].mean()

        # Calculate different addresses and DeFi stats if available
        if data['different_addresses'] is not None:
            avg_daily_different_addresses = data['different_addresses'].mean()
            max_daily_different_addresses = data['different_addresses'].max()

        if data['defi_transaction_count'] is not None:
            avg_daily_defi_transactions = data['defi_transaction_count'].mean()
            max_daily_defi_transactions = data['defi_transaction_count'].max()

        if data['rollup_transaction_count'] is not None:
            avg_daily_rollup_transactions = (
                data['rollup_transaction_count'].mean())
            max_daily_rollup_transactions = (
                data['rollup_transaction_count'].max())

        print("\n{}:".format(stablecoin_name.upper()))
        print("  Total Volume: {:.2f} tokens".format(
            total_volume))
        print("  Total Transactions: {:,}".format(total_transactions))
        print("  Average Daily Volume: {:.2f} tokens".format(
            avg_daily_volume))
        print("  Average Daily Transactions: {:.0f}".format(
            avg_daily_transactions))
        if data['different_addresses'] is not None:
            print("  Average Daily Different Addresses: {:.0f}".format(
                avg_daily_different_addresses))
            print("  Max Daily Different Addresses: {:,}".format(
                max_daily_different_addresses))
        if data['defi_transaction_count'] is not None:
            print("  Average Daily DeFi Transactions: {:.0f}".format(
                avg_daily_defi_transactions))
            print("  Max Daily DeFi Transactions: {:,}".format(
                max_daily_defi_transactions))
        if data['rollup_transaction_count'] is not None:
            print("  Average Daily Rollup Transactions: {:.0f}".format(
                avg_daily_rollup_transactions))
            print("  Max Daily Rollup Transactions: {:,}".format(
                max_daily_rollup_transactions))


def main():
    """Main function to create both plots"""
    print("Stablecoin Visualization Script")
    print("="*40)

    # Load data from CSV files
    stablecoin_data = load_stablecoin_data()

    if not stablecoin_data:
        print("No stablecoin data found! Make sure you have run "
              "stats.py first.")
        return

    print("\nLoaded data for {} stablecoins".format(
        len(stablecoin_data)))

    # Create the plots
    print("\nCreating volume plot...")
    create_volume_plot(stablecoin_data)

    print("Creating transaction count plot...")
    create_transaction_count_plot(stablecoin_data)

    print("Creating different addresses plot...")
    create_different_addresses_plot(stablecoin_data)

    print("Creating DeFi transactions plot...")
    create_defi_transactions_plot(stablecoin_data)

    print("Creating Rollup transactions plot...")
    create_rollup_transactions_plot(stablecoin_data)

    # Print summary statistics
    print_summary_stats(stablecoin_data)

    print("\n" + "="*40)
    print("Visualization complete!")
    print("Generated files:")
    print("  - stablecoin_volume_plot.png")
    print("  - stablecoin_transaction_count_plot.png")
    print("  - stablecoin_different_addresses_plot.png")
    print("  - stablecoin_defi_transactions_plot.png")
    print("  - stablecoin_rollup_transactions_plot.png")


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
"""
Stablecoin Visualization Script

This script reads the CSV files generated by stats.py and creates two plots:
1. Daily transacted volume for all stablecoins
2. Daily transaction count for all stablecoins

Both plots show days on the x-axis with different colors for each stablecoin
and include legends.
"""

import glob

import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.use('Agg')  # Use non-interactive backend


def load_stablecoin_data():
    """Load all available stablecoin daily stats CSV files"""
    stablecoin_data = {}

    # Find all daily stats CSV files
    csv_files = glob.glob("*_daily_stats.csv")

    print("Found {} stablecoin data files:".format(
        len(csv_files)))

    for csv_file in csv_files:
        # Extract stablecoin name from filename
        stablecoin_name = csv_file.replace("_daily_stats.csv", "")

        try:
            # Read the CSV file
            df = pd.read_csv(csv_file)

            # Convert date column to datetime
            df['date'] = pd.to_datetime(df['date'])

            # Extract volume and transaction count columns
            volume_col = "total_volume_{}".format(stablecoin_name)
            tx_count_col = "transaction_count"

            if volume_col in df.columns and tx_count_col in df.columns:
                # Store the data
                stablecoin_data[stablecoin_name] = {
                    'dates': df['date'],
                    'volume': df[volume_col],
                    'transaction_count': df[tx_count_col]
                }
                print("  ✓ {}: {} days of data".format(
                    stablecoin_name.upper(), len(df)))
            else:
                print("  ✗ {}: Missing required columns".format(
                    stablecoin_name.upper()))

        except Exception as e:
            print("  ✗ {}: Error reading file - {}".format(
                stablecoin_name.upper(), e))

    return stablecoin_data


def create_volume_plot(stablecoin_data):
    """Create a plot showing daily transacted volume for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['volume'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='o',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Volume',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Volume (Tokens)', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_volume_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Volume plot saved as 'stablecoin_volume_plot.png'")

    return plt


def create_transaction_count_plot(stablecoin_data):
    """Create a plot showing daily transaction count for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as volume plot)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['transaction_count'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='s',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Count',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_transaction_count_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Transaction count plot saved as "
          "'stablecoin_transaction_count_plot.png'")

    return plt


def print_summary_stats(stablecoin_data):
    """Print summary statistics for all stablecoins"""
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    for stablecoin_name, data in stablecoin_data.items():
        total_volume = data['volume'].sum()
        total_transactions = data['transaction_count'].sum()
        avg_daily_volume = data['volume'].mean()
        avg_daily_transactions = data['transaction_count'].mean()

        print("\n{}:".format(stablecoin_name.upper()))
        print("  Total Volume: {:.2f} tokens".format(
            total_volume))
        print("  Total Transactions: {:,}".format(total_transactions))
        print("  Average Daily Volume: {:.2f} tokens".format(
            avg_daily_volume))
        print("  Average Daily Transactions: {:.0f}".format(
            avg_daily_transactions))


def main():
    """Main function to create both plots"""
    print("Stablecoin Visualization Script")
    print("="*40)

    # Load data from CSV files
    stablecoin_data = load_stablecoin_data()

    if not stablecoin_data:
        print("No stablecoin data found! Make sure you have run "
              "stats.py first.")
        return

    print("\nLoaded data for {} stablecoins".format(
        len(stablecoin_data)))

    # Create the plots
    print("\nCreating volume plot...")
    create_volume_plot(stablecoin_data)

    print("Creating transaction count plot...")
    create_transaction_count_plot(stablecoin_data)

    # Print summary statistics
    print_summary_stats(stablecoin_data)

    print("\n" + "="*40)
    print("Visualization complete!")
    print("Generated files:")
    print("  - stablecoin_volume_plot.png")
    print("  - stablecoin_transaction_count_plot.png")


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
"""
Stablecoin Visualization Script

This script reads the CSV files generated by stats.py and creates two plots:
1. Daily transacted volume for all stablecoins
2. Daily transaction count for all stablecoins

Both plots show days on the x-axis with different colors for each stablecoin
and include legends.
"""

import glob

import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.use('Agg')  # Use non-interactive backend


def load_stablecoin_data():
    """Load all available stablecoin daily stats CSV files"""
    stablecoin_data = {}

    # Find all daily stats CSV files
    csv_files = glob.glob("*_daily_stats.csv")

    print("Found {} stablecoin data files:".format(
        len(csv_files)))

    for csv_file in csv_files:
        # Extract stablecoin name from filename
        stablecoin_name = csv_file.replace("_daily_stats.csv", "")

        try:
            # Read the CSV file
            df = pd.read_csv(csv_file)

            # Convert date column to datetime
            df['date'] = pd.to_datetime(df['date'])

            # Extract volume and transaction count columns
            volume_col = "total_volume_{}".format(stablecoin_name)
            tx_count_col = "transaction_count"

            if volume_col in df.columns and tx_count_col in df.columns:
                # Store the data
                stablecoin_data[stablecoin_name] = {
                    'dates': df['date'],
                    'volume': df[volume_col],
                    'transaction_count': df[tx_count_col]
                }
                print("  ✓ {}: {} days of data".format(
                    stablecoin_name.upper(), len(df)))
            else:
                print("  ✗ {}: Missing required columns".format(
                    stablecoin_name.upper()))

        except Exception as e:
            print("  ✗ {}: Error reading file - {}".format(
                stablecoin_name.upper(), e))

    return stablecoin_data


def create_volume_plot(stablecoin_data):
    """Create a plot showing daily transacted volume for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['volume'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='o',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Volume',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Volume (Tokens)', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_volume_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Volume plot saved as 'stablecoin_volume_plot.png'")

    return plt


def create_transaction_count_plot(stablecoin_data):
    """Create a plot showing daily transaction count for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as volume plot)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['transaction_count'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='s',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Count',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_transaction_count_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Transaction count plot saved as "
          "'stablecoin_transaction_count_plot.png'")

    return plt


def print_summary_stats(stablecoin_data):
    """Print summary statistics for all stablecoins"""
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    for stablecoin_name, data in stablecoin_data.items():
        total_volume = data['volume'].sum()
        total_transactions = data['transaction_count'].sum()
        avg_daily_volume = data['volume'].mean()
        avg_daily_transactions = data['transaction_count'].mean()

        print("\n{}:".format(stablecoin_name.upper()))
        print("  Total Volume: {:.2f} tokens".format(
            total_volume))
        print("  Total Transactions: {:,}".format(total_transactions))
        print("  Average Daily Volume: {:.2f} tokens".format(
            avg_daily_volume))
        print("  Average Daily Transactions: {:.0f}".format(
            avg_daily_transactions))


def main():
    """Main function to create both plots"""
    print("Stablecoin Visualization Script")
    print("="*40)

    # Load data from CSV files
    stablecoin_data = load_stablecoin_data()

    if not stablecoin_data:
        print("No stablecoin data found! Make sure you have run "
              "stats.py first.")
        return

    print("\nLoaded data for {} stablecoins".format(
        len(stablecoin_data)))

    # Create the plots
    print("\nCreating volume plot...")
    create_volume_plot(stablecoin_data)

    print("Creating transaction count plot...")
    create_transaction_count_plot(stablecoin_data)

    # Print summary statistics
    print_summary_stats(stablecoin_data)

    print("\n" + "="*40)
    print("Visualization complete!")
    print("Generated files:")
    print("  - stablecoin_volume_plot.png")
    print("  - stablecoin_transaction_count_plot.png")


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
"""
Stablecoin Visualization Script

This script reads the CSV files generated by stats.py and creates two plots:
1. Daily transacted volume for all stablecoins
2. Daily transaction count for all stablecoins

Both plots show days on the x-axis with different colors for each stablecoin
and include legends.
"""

import glob

import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.use('Agg')  # Use non-interactive backend


def load_stablecoin_data():
    """Load all available stablecoin daily stats CSV files"""
    stablecoin_data = {}

    # Find all daily stats CSV files
    csv_files = glob.glob("*_daily_stats.csv")

    print("Found {} stablecoin data files:".format(
        len(csv_files)))

    for csv_file in csv_files:
        # Extract stablecoin name from filename
        stablecoin_name = csv_file.replace("_daily_stats.csv", "")

        try:
            # Read the CSV file
            df = pd.read_csv(csv_file)

            # Convert date column to datetime
            df['date'] = pd.to_datetime(df['date'])

            # Extract volume and transaction count columns
            volume_col = "total_volume_{}".format(stablecoin_name)
            tx_count_col = "transaction_count"

            if volume_col in df.columns and tx_count_col in df.columns:
                # Store the data
                stablecoin_data[stablecoin_name] = {
                    'dates': df['date'],
                    'volume': df[volume_col],
                    'transaction_count': df[tx_count_col]
                }
                print("  ✓ {}: {} days of data".format(
                    stablecoin_name.upper(), len(df)))
            else:
                print("  ✗ {}: Missing required columns".format(
                    stablecoin_name.upper()))

        except Exception as e:
            print("  ✗ {}: Error reading file - {}".format(
                stablecoin_name.upper(), e))

    return stablecoin_data


def create_volume_plot(stablecoin_data):
    """Create a plot showing daily transacted volume for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['volume'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='o',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Volume',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Volume (Tokens)', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_volume_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Volume plot saved as 'stablecoin_volume_plot.png'")

    return plt


def create_transaction_count_plot(stablecoin_data):
    """Create a plot showing daily transaction count for all stablecoins"""
    plt.figure(figsize=(12, 8))

    # Define colors for different stablecoins (same as volume plot)
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for i, (stablecoin_name, data) in enumerate(stablecoin_data.items()):
        color = colors[i % len(colors)]
        plt.plot(data['dates'], data['transaction_count'],
                 label=stablecoin_name.upper(),
                 color=color,
                 linewidth=2,
                 marker='s',
                 markersize=4)

    plt.title('Daily Stablecoin Transaction Count',
              fontsize=16, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Transactions', fontsize=12)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)

    # Format x-axis to show dates nicely
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=3))
    plt.xticks(rotation=45)

    # Format y-axis to show large numbers with commas and set log scale
    ax = plt.gca()
    ax.set_yscale('log')
    ax.yaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, p: '{:,.0f}'.format(x)))

    plt.tight_layout()
    plt.savefig('stablecoin_transaction_count_plot.png',
                dpi=300, bbox_inches='tight')
    print("✓ Transaction count plot saved as "
          "'stablecoin_transaction_count_plot.png'")

    return plt


def print_summary_stats(stablecoin_data):
    """Print summary statistics for all stablecoins"""
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    for stablecoin_name, data in stablecoin_data.items():
        total_volume = data['volume'].sum()
        total_transactions = data['transaction_count'].sum()
        avg_daily_volume = data['volume'].mean()
        avg_daily_transactions = data['transaction_count'].mean()

        print("\n{}:".format(stablecoin_name.upper()))
        print("  Total Volume: {:.2f} tokens".format(
            total_volume))
        print("  Total Transactions: {:,}".format(total_transactions))
        print("  Average Daily Volume: {:.2f} tokens".format(
            avg_daily_volume))
        print("  Average Daily Transactions: {:.0f}".format(
            avg_daily_transactions))


def main():
    """Main function to create both plots"""
    print("Stablecoin Visualization Script")
    print("="*40)

    # Load data from CSV files
    stablecoin_data = load_stablecoin_data()

    if not stablecoin_data:
        print("No stablecoin data found! Make sure you have run "
              "stats.py first.")
        return

    print("\nLoaded data for {} stablecoins".format(
        len(stablecoin_data)))

    # Create the plots
    print("\nCreating volume plot...")
    create_volume_plot(stablecoin_data)

    print("Creating transaction count plot...")
    create_transaction_count_plot(stablecoin_data)

    # Print summary statistics
    print_summary_stats(stablecoin_data)

    print("\n" + "="*40)
    print("Visualization complete!")
    print("Generated files:")
    print("  - stablecoin_volume_plot.png")
    print("  - stablecoin_transaction_count_plot.png")


if __name__ == "__main__":
    main()


